<?php

namespace Venture\Home\Filament\Resources\UserResource\Pages\ViewUser;

use Filament\Actions\Action;
use Filament\Forms\Components\TextInput;
use Illuminate\Database\Eloquent\Model;

class PasswordAction extends Action
{
    protected string $langPre = 'home::filament/resources/user/pages/view.actions.password';

    public static function getDefaultName(): ?string
    {
        return 'password';
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->modalHeading(__("{$this->langPre}.heading"));

        $this->modalDescription(__("{$this->langPre}.description"));

        $this->successNotificationTitle(__("{$this->langPre}.notifications.success.title"));

        $this->form([
            TextInput::make('password')
                ->label("{$this->langPre}.fields.password.label")
                ->translateLabel()
                ->password()
                ->revealable()
                ->confirmed()
                ->required(),

            TextInput::make('password_confirmation')
                ->label("{$this->langPre}.fields.password_confirmation.label")
                ->translateLabel()
                ->password()
                ->revealable()
                ->required(),
        ]);

        $this->action(function (array $data, Model $record): void {
            $record->update([
                'password' => $data['password'],
            ]);

            $this->success();
        });
    }
}
