<?php

namespace Venture\Home\Filament\Resources\TemporaryFileResource\Tables\Actions;

use Filament\Tables\Actions\Action;
use Illuminate\Database\Eloquent\Model;

class DownloadAction extends Action
{
    protected string $langPre = 'home::filament/resources/temporary-file/tables/actions/download';

    public static function getDefaultName(): ?string
    {
        return 'download';
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->label(__("{$this->langPre}.label"));

        $this->icon('fad:sharp-download');

        $this->url(function (Model $record) {
            return $record->downloadUrl();
        });

        $this->openUrlInNewTab();
    }
}
